### ISSUE TITLE
Get-ADDBAccount : An item with the same key has already been added.

### ISSUE THREAD

**Issue by cruxofit** [MichaelGrafnetter/DSInternals#118]
Hello, I am receiving the following error when running the Get-ADDBAccount command to audit our active directory password quality.

Thank you for any help you can provide.

Command: ($bootKey is set using the Get-Bootkey cmdlet)
`Get-ADDBAccount -All -DatabasePath 'D:\Database\ntds\ActiveDirectory\ntds.dit' -BootKey $bootKey |
            Test-PasswordQuality -WeakPasswordHashesSortedFile pwned-passwords-ntlm-ordered-by-hash-v5.txt`

Full Error:

```Get-ADDBAccount : An item with the same key has already been added.
At line:2 char:1
+ Get-ADDBAccount -All -DatabasePath 'D:\Database\ntds\ActiveDirectory\ntds.dit' -BootKe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Get-ADDBAccount], ArgumentException
    + FullyQualifiedErrorId : DBContextError,DSInternals.PowerShell.Commands.GetADDBAccountCommand

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DSInternals.DataStore.DirectorySchema.LoadAttributeProperties(Cursor dataTableCursor) in d:\a\1\s\Src\DSInternals.DataStore\DirectorySchema.cs:line 255
   at DSInternals.DataStore.DirectorySchema..ctor(IsamDatabase database) in d:\a\1\s\Src\DSInternals.DataStore\DirectorySchema.cs:line 39
   at DSInternals.DataStore.DirectoryContext..ctor(String dbFilePath, Boolean readOnly, String logDirectoryPath) in d:\a\1\s\Src\DSInternals.DataStore\DirectoryContext.cs:line 100
   at DSInternals.PowerShell.Commands.ADDBCommandBase.BeginProcessing()

**Comment by MichaelGrafnetter** [comment]
@cruxofit Could you please look into the AD schema? Is there any attribute that was deleted / inactivated, so that I can replicate it in my test environment?

**Comment by yanncam** [comment]
Hello,

I meet the same issue on a ntds.dit file via `Get-ADDBAccount` with the `-All` or a specific user like `-SamAccountName krbtgt`.

Here my output with the stacktrace `$Error[0].Exception.StackTrace` :

```
PS C:\ntds-dump> $key = Get-BootKey -SystemHiveFilePath 'SYSTEM'
PS C:\ntds-dump> Get-ADDBAccount -All -BootKey $key -DatabasePath ".\ntds.dit"
Get-ADDBAccount : Un élément avec la même clé a déjà été ajouté.
Au caractère Ligne:1 : 1
+ Get-ADDBAccount -All -BootKey $key -DatabasePath ".\ntds.dit"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Get-ADDBAccount], ArgumentException
    + FullyQualifiedErrorId : DBContextError,DSInternals.PowerShell.Commands.GetADDBAccountCommand

PS C:\ntds-dump> $Error[0].Exception.StackTrace
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à DSInternals.DataStore.DirectorySchema.LoadAttributeProperties(Cursor dataTableCursor) dans d:\a\1\s\Src\DSInternals.DataStore\DirectorySchema.cs:ligne 255
   à DSInternals.DataStore.DirectorySchema..ctor(IsamDatabase database) dans d:\a\1\s\Src\DSInternals.DataStore\DirectorySchema.cs:ligne 39
   à DSInternals.DataStore.DirectoryContext..ctor(String dbFilePath, Boolean readOnly, String logDirectoryPath) dans d:\a\1\s\Src\DSInternals.DataStore\DirectoryContext.cs:ligne 100
   à DSInternals.PowerShell.Commands.ADDBCommandBase.BeginProcessing()
PS C:\ntds-dump> Get-ADDBAccount -SamAccountName krbtgt -BootKey $key -DatabasePath ".\ntds.dit"
Get-ADDBAccount : Un élément avec la même clé a déjà été ajouté.
Au caractère Ligne:1 : 1
+ Get-ADDBAccount -SamAccountName krbtgt -BootKey $key -DatabasePath ". ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Get-ADDBAccount], ArgumentException
    + FullyQualifiedErrorId : DBContextError,DSInternals.PowerShell.Commands.GetADDBAccountCommand

PS C:\ntds-dump> $Error[1].Exception.StackTrace
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à DSInternals.DataStore.DirectorySchema.LoadAttributeProperties(Cursor dataTableCursor) dans d:\a\1\s\Src\DSInternals.DataStore\DirectorySchema.cs:ligne 255
   à DSInternals.DataStore.DirectorySchema..ctor(IsamDatabase database) dans d:\a\1\s\Src\DSInternals.DataStore\DirectorySchema.cs:ligne 39
   à DSInternals.DataStore.DirectoryContext..ctor(String dbFilePath, Boolean readOnly, String logDirectoryPath) dans d:\a\1\s\Src\DSInternals.DataStore\DirectoryContext.cs:ligne 100
   à DSInternals.PowerShell.Commands.ADDBCommandBase.BeginProcessing()
PS C:\ntds-dump>
```

The same error  `An item with the same key has already been added.` is displayed in both cases in french :  `Un élément avec la même clé a déjà été ajouté.`.

Thank you for any help you can provide, and I remain available for any further information,

Have a nice day,

**Comment by MichaelGrafnetter** [comment]
@yanncam Thanks for the report. I thought about it and I suspect that a schema attribute had been disabled in your AD environment an then re-created. Could you please confirm this? If so, I will need to create such situation in my test environment to troubleshoot it.

**Comment by yanncam** [comment]
> @yanncam Thanks for the report. I thought about it and I suspect that a schema attribute had been disabled in your AD environment an then re-created. Could you please confirm this? If so, I will need to create such situation in my test environment to troubleshoot it.

Hello @MichaelGrafnetter,

I spoke with the IT team that manages the Active Directory and is in charge of the NTDS.dit export, and according to them no manual nor custom modification of the schema has been made. With the exception of the installation of Service Packs for Exchange.

Moreover, rather than querying the NTDS.dit offline via `Get-ADDBAccount` (which generates the bug detailed above), we tried online via `Get-ADReplAccount` and there, no problem to retrieve the data !

Could there be an explanation of why `Get-ADDBAccount` is problematic offline while `Get-ADReplAccount` is running smoothly on the same Active Directory / NTDS.dit?

Thank you for your support and have a nice day,

**Comment by yanncam** [comment]
@MichaelGrafnetter,

As predicted, there are two custom attributes with the same name but different case in the schema, so yes, it looks like there has been some customization of the schema in the past.

I have made the following Powershell commandline to list all values of `lDAPDisplayName` attribute for all objectClass `attributeSchema` in the search-base `CN=Schema,CN=Configuration,DC=X,DC=Y` :

```
Get-ADObject -LDAPFilter "(objectClass=attributeSchema)" -SearchBase "CN=Schema,CN=Configuration,DC=X,DC=Y" -Properties distinguishedName,lDAPDisplayName,objectClass -Server X.Y | select distinguishedName,lDAPDisplayName,objectClass | Export-Csv -Path .\lDAPDisplayName.csv -NoTypeInformation -Delimiter ';'
```

From the output CSV file, I identified the 2 following duplicated attributes (name anonymised but case respected):

```
dn: CN=MYCUSTOM_ATTRIBUTE,CN=Schema,CN=Configuration,DC=X,DC=Y
objectClass: attributeSchema
lDAPDisplayName: mYCUSTOMATTRIBUTE

dn: CN=mycustomattribute,CN=Schema,CN=Configuration,DC=X,DC=Y
objectClass: attributeSchema
lDAPDisplayName: mycustomattribute
```

I think it's the cause of the issue.

Here after the details of the two duplicated objects (with attribute name anonymized or redacted but case sensitive):

```
> Get-ADObject -LDAPFilter "(&(lDAPDisplayName=mycustomattribute)(objectClass=attributeSchema))" -SearchBase "CN=mycustomattribute,CN=Schema,CN=Configuration,DC=X,DC=Y" -Properties * -Server X.Y

adminDisplayName                : mycustomattribute
attributeID                     : 1.2.840.113556.1.8000.2554.5605.49619.44522.16784.39989.16021004.12306991
attributeSyntax                 : 2.5.5.4
CanonicalName                   : x.y/Configuration/Schema/mycustomattribute
CN                              : mycustomattribute
Created                         : 10.05.2019 16:39:50
createTimeStamp                 : 10.05.2019 16:39:50
Deleted                         :
Description                     :
DisplayName                     :
DistinguishedName               : CN=mycustomattribute,CN=Schema,CN=Configuration,DC=X,DC=Y
dSCorePropagationData           : {01.01.1601 01:00:00}
instanceType                    : 4
isDeleted                       :
isSingleValued                  : True
LastKnownParent                 :
lDAPDisplayName                 : mycustomattribute
Modified                        : 10.05.2019 16:39:50
modifyTimeStamp                 : 10.05.2019 16:39:50
msDS-IntId                      : -1973970740
Name                            : mycustomattribute
nTSecurityDescriptor            : System.DirectoryServices.ActiveDirectorySecurity
ObjectCategory                  : CN=Attribute-Schema,CN=Schema,CN=Configuration,DC=X,DC=Y
ObjectClass                     : attributeSchema
ObjectGUID                      : a5a93cd4-f8c7-46bd-9c49-e9aff600e732
oMSyntax                        : 20
ProtectedFromAccidentalDeletion : False
schemaIDGUID                    : {105, 211, 49, 44...}
sDRightsEffective               : 15
showInAdvancedViewOnly          : True
uSNChanged                      : 46201928
uSNCreated                      : 46201928
whenChanged                     : 10.05.2019 16:39:50
whenCreated                     : 10.05.2019 16:39:50
```

And the second:

```
> Get-ADObject -LDAPFilter "(&(lDAPDisplayName=mYCUSTOMATTRIBUTE)(objectClass=attributeSchema))" -SearchBase "CN=MYCUSTOM_ATTRIBUTE,CN=Schema,CN=Configuration,DC=X,DC=Y" -Properties * -Server X.Y

adminDescription                : [REDACTED]
adminDisplayName                : MYCUSTOM_ATTRIBUTE
attributeID                     : 1.2.840.113556.1.8000.2554.26753.36617.51914.17888.42991.11840279.586380
attributeSyntax                 : 2.5.5.4
CanonicalName                   : X.Y/Configuration/Schema/MYCUSTOM_ATTRIBUTE
CN                              : MYCUSTOM_ATTRIBUTE
Created                         : 10.05.2019 11:17:10
createTimeStamp                 : 10.05.2019 11:17:10
Deleted                         :
Description                     :
DisplayName                     :
DistinguishedName               : CN=MYCUSTOM_ATTRIBUTE,CN=Schema,CN=Configuration,DC=X,DC=Y
dSCorePropagationData           : {01.01.1601 01:00:00}
instanceType                    : 4
isDefunct                       : True
isDeleted                       :
isSingleValued                  : True
LastKnownParent                 :
lDAPDisplayName                 : mYCUSTOMATTRIBUTE
Modified                        : 10.05.2019 16:38:11
modifyTimeStamp                 : 10.05.2019 16:38:11
msDS-IntId                      : -1985647957
Name                            : MYCUSTOM_ATTRIBUTE
nTSecurityDescriptor            : System.DirectoryServices.ActiveDirectorySecurity
ObjectCategory                  : CN=Attribute-Schema,CN=Schema,CN=Configuration,DC=X,DC=Y
ObjectClass                     : attributeSchema
ObjectGUID                      : 06f638d9-a9f3-421a-b779-4c3114d59033
oMSyntax                        : 20
ProtectedFromAccidentalDeletion : False
schemaIDGUID                    : {105, 24, 24, 229...}
sDRightsEffective               : 15
showInAdvancedViewOnly          : True
uSNChanged                      : 46201846
uSNCreated                      : 46191627
whenChanged                     : 10.05.2019 16:38:11
whenCreated                     : 10.05.2019 11:17:10
```

I hope it will help,

Thank you very much,
