### ISSUE TITLE
Version DSInternals version : 4.4.0: System.FormatException: CRC check failed.

### ISSUE THREAD

**Issue by ThalesVinayak** [MichaelGrafnetter/DSInternals#136]
Hi ,

We wanted to share information about the exception faced with  DSInternals.Replication.DirectoryReplicationClient.GetAccount.
we are getting below mentioned exception while using the DSInternals.Replication.DirectoryReplicationClient.GetAccount method. All the users in AD are populated with the passwords, whenever we try to use this  GetAccount method to get passwordhash, it throws an the exception for random users. For example, on an average if we have 200 users to get password hash, GetAccount  throws an exception for at least 2-3 users.

We have recently upgraded our application from version 2.21.0.0 to 4.4.0.0. While using version 2.21.0.0, there is no such exception thrown by the GetAccount method.

System.FormatException: CRC check failed.
   at DSInternals.Common.Validator.AssertCrcMatches(Byte[] buffer, UInt32 expectedCrc)
   at DSInternals.Replication.ReplicationSecretDecryptor.DecryptSecret(Byte[] blob)
   at DSInternals.Common.Data.DSAccount.LoadHashes(DirectoryObject dsObject, DirectorySecretDecryptor pek)
   at DSInternals.Replication.DirectoryReplicationClient.GetAccount(String distinguishedName)
   at ADUserAdapter.ActiveDirectory.ActiveDirectoryService.GetPasswordHash(String userDistinguishedName)
   at ADUserAdapter.ActiveDirectory.ActiveDirectoryService.GetPasswordHash(String userDistinguishedName)

Kindly suggest

**Comment by MichaelGrafnetter** [comment]
Hello @ThalesVinayak , are you please able to replicate the bug in a test environment? From what Windows Server version are you replicating the data?

**Comment by ThalesVinayak** [comment]
@MichaelGrafnetter thanks for the reply.  yes, bug is reproducible in test environment as well. server used is WIN2012R2. Issue was not reproducible with 10-20 users in AD. I tried with around 200 users and I always faced this exception for at least 2-3 users. In every syncing iteration there are random users for which the exception is faced and password hash is calculated as null In every subsequent sync, the users failed in previous attempt works fine and another random 2-3 fails. Please let me know if you need  more information about the issue.

**Comment by ThalesVinayak** [comment]
Hi @MichaelGrafnetter I have further investigated the issue that we are facing. After debugging the code for DSinternals, I came to know that the blob which is getting read under LoadHashes method is getting different from actual one:

**dsObject.ReadAttribute(CommonDirectoryAttributes.NTHash, out encryptedNtHash);**

this encryptedNthash value blob gets changed for random users and when this blob is passed to DecryptSecret method of ReplicationSecretDecryptor class. validation fails while doing the CRC check as actual value is not equal to the expected value of CRC.

this.NTHash = pek.DecryptHash(encryptedNtHash, this.Sid.GetRid()); >>>> byte[] partiallyDecryptedHash = this.DecryptSecret(blob); >>> public override byte[] DecryptSecret(byte[] blob)


below is success and fail case for same user:

failure case: 

2021-12-31:12:09:28 AM [7] WARN  ClientLauncher - ReplicationSecretDecryptor: decrypted secret:gäHÝÝ¡l|Äíàñ	ýí expected **crc:3918247760 actual:385695902.**

success case for the same user:

2021-12-31:12:11:30 AM [13] WARN  ClientLauncher - ReplicationSecretDecryptor: decrypted secret:i¯ƒü„	:_ùÀ&ñw½hQ **expected crc:762667822 actual:762667822.**

**Comment by ThalesVinayak** [comment]
Hi @MichaelGrafnetter , I have further investigated the issue on my end and debugged DSinternals to see what exactly the issue can be.

Under DSAccounts class method "LoadHashes", the blob encryptedNtHash read by below line changes to different value.
**dsObject.ReadAttribute(CommonDirectoryAttributes.NTHash, out encryptedNtHash);**

when this corrupted blob is passed to DecryptSecret method of ReplicationSecretDecryptor class, CRC validation fails as expected CRC value is different from the actual decryptedSecret.

Below is the result for one user:
**fail case:**

2021-12-31:12:09:28 AM [7] WARN  ClientLauncher - ReplicationSecretDecryptor: decrypted secret:gäHÝÝ¡l|Äíàñ	ýí expected crc:3918247760 actual:385695902.

**success case:** 
2021-12-31:12:11:30 AM [13] WARN  ClientLauncher - ReplicationSecretDecryptor: decrypted secret:i¯ƒü„	:_ùÀ&ñw½hQ expected crc:762667822 actual:762667822

**Comment by ThalesVinayak** [comment]
@MichaelGrafnetter  issue is reproducible on windows server 2019 standard as well. @andrei-galkin

**Comment by ThalesVinayak** [comment]
@MichaelGrafnetter we further investigated the issue, we reverted back to all the previous version of DSInternals and identified that issue started to happen when DSinternal was upgraded from 4.1 to 4.2(**multi-domain/forest support to Test-PasswordQuality**) and below is the commit which has brought in the issue

_**https://github.com/MichaelGrafnetter/DSInternals/commit/4bd98076879cdb91c77383a8d37630ad031e708e**_

Particularly the issue is with the file _**https://github.com/MichaelGrafnetter/DSInternals/commit/4bd98076879cdb91c77383a8d37630ad031e708e#diff-8897063dea57c61fae8eefd70f5fdb014df6025a3b263b8e44e07ff65b1a6a2a**_
Under the method  **DSAccount GetAccount(string distinguishedName)**, the **NetBIOSDomainName** value is passed to instantiate DSAccount.   I tried passing hard coded valid value for NetBIOSDomainName instead of calculating it and no such exception was thrown. so the issue seems to be happening while evaluating NetBIOSDomainName which is getting missed for some of the users. Please see if this is the root cause.    FYI  @andrei-galkin

**Comment by MichaelGrafnetter** [comment]
Thanks @ThalesVinayak , I will look into it.

**Comment by ThalesVinayak** [comment]
Hi @MichaelGrafnetter, we are able to resolve the issue by using below line in our code.

replicationClient.Dispose();
replicationClient = null;

I think we can close this issue. Thank you

**Comment by MichaelGrafnetter** [comment]
Hello @ThalesVinayak , I still was not able to replicate this issue. I received a similar report yesterday and it seems to be caused by a non-US version of Windows Server DC. Could you please share what language version you have on the affected DC?
Another suspicion of mine is some out-of-band session key change.

**Comment by ThalesVinayak** [comment]
Hello @MichaelGrafnetter, the language version is  0409/en-US/English - United States. 

In our case, we were not disposing replication client created and as a result related DRS connections were not getting disposed off as well. After reaching a threshold they were creating the issue around evaluating NetBiosDomainName(evaluated via lazy loading).

**Comment by GuyTe** [comment]
@MichaelGrafnetter FYI, we had something similar throwing same CRC errors and have chased down to the session key changing mid-page (part of returned objects secrets are encrypted using SK1 and the rest using SK2). There is a callback in the DrsConnection class that is fired when the session key changes. It updates the SessionKey in DrsConnection, but I assume that the secrets decryption code is still using the SK obtained when DrsConnection was instantiated.

Naive approach would be to re-read the page while using latest session key (might still be problematic in some cases). 
Better approach would be to try to decrypt using latest session key.
The issue has less chances to happen when requesting smaller pages.

The way to repro:
- Use GetNCChanges untill noMoreData and save the replication cookie
- perform a massive passwords change to multiple AD accounts 
- call for GetNCChanges using the saved cookie

**Comment by MichaelGrafnetter** [comment]
WOW, thanks @GuyTe for explaining the problem and for the repro steps. This is new to me. I will need to figure out a better way of propagating the session key update.
