### ISSUE TITLE
Get-ADDBAccount : Invalid file path

### ISSUE THREAD

**Issue by m7x** [MichaelGrafnetter/DSInternals#16]
Hello,

For some reasons  ```Get-ADDBAccount``` doesn't load the ntds.file:

```
PS C:\Users\Administrator\Downloads\DSInternals_v2.14\DSInternals>
PS C:\Users\Administrator\Downloads\DSInternals_v2.14\DSInternals> echo $key
5c4445b6782e70f9a0be268ba2c401ee
PS C:\Users\Administrator\Downloads\DSInternals_v2.14\DSInternals> dir C:\ntds.dit

    Directory: C:\

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         5/16/2016  12:42 PM   16793600 ntds.dit
PS C:\Users\Administrator\Downloads\DSInternals_v2.14\DSInternals> Get-ADDBAccount -All -DBPath 'C:\ntds.dit' -BootKey $key
Get-ADDBAccount : Invalid file path
At line:1 char:1
+ Get-ADDBAccount -All -DBPath 'C:\ntds.dit' -BootKey $key
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Get-ADDBAccount], EsentInvalidPathException
    + FullyQualifiedErrorId : DBContextError,DSInternals.PowerShell.Commands.GetADDBAccountCommand

PS C:\Users\Administrator\Downloads\DSInternals_v2.14\DSInternals>
```

Any suggestions?

Thanks

**Comment by MichaelGrafnetter** [comment]
Unfortunately, I was not able to replicate the problem. Does it work in other directories than c:\ ? Do you have write permissions to the file? Could you please provide some details on the exception that has been thrown using this command " $Error[0].Exception | select * "? Thx.

**Comment by m7x** [comment]
I have changed the directory of the ntds file and I have a different error. Yes, I have write permissions. I am administrator. 

```
PS C:\> Get-ADDBAccount -All -DBPath 'C:\TEMP\ntds.dit' -BootKey $key
Get-ADDBAccount : Method not found: 'Int32 System.Environment.get_CurrentManagedThreadId()'.
At line:1 char:1
+ Get-ADDBAccount -All -DBPath 'C:\TEMP\ntds.dit' -BootKey $key
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Get-ADDBAccount], MissingMethodException
    + FullyQualifiedErrorId : DBContextError,DSInternals.PowerShell.Commands.GetADDBAccountCommand

PS C:\> $Error[0].Exception | select *


Message        : Method not found: 'Int32 System.Environment.get_CurrentManagedThreadId()'.
Data           : {}
InnerException :
TargetSite     : Void .ctor(Int32)
StackTrace     :    at DSInternals.DataStore.LinkResolver.<GetLinkedDNTags>d__0..ctor(Int32 <>1__state)
                    at DSInternals.DataStore.LinkResolver.GetLinkedDNTag(Int32 dnTag, String attributeName)
                    at DSInternals.DataStore.DomainController..ctor(DirectoryContext context)
                    at DSInternals.DataStore.DirectoryContext..ctor(String dbFilePath, Boolean readOnly, String
                 logDirectoryPath)
                    at DSInternals.PowerShell.Commands.ADDBCommandBase.BeginProcessing()
HelpLink       :
Source         : DSInternals.DataStore
```

Thanks

**Comment by MichaelGrafnetter** [comment]
Could you please upgrading .NET Framework to 4.5.1+? PowerShell somehow ignores the minimum version stated in the module manifest.

**Comment by MichaelGrafnetter** [comment]
It has been confirmed that PS prior to version 5 ignores the .NET Framework minimum version requirement. Implementing my own checks would be cumbersome.
