### ISSUE TITLE
Error using Get-ADReplAccount: An item with the same key has already been added.

### ISSUE THREAD

**Issue by CamFlyerCH** [MichaelGrafnetter/DSInternals#40]
Hello
I use this function to synchronize password hashes from a old to a new domain. Works fine but on 6 of 1440 user accounts I get an error:

Commandline:
`Get-ADReplAccount -SamAccountName U123456 -Domain CONTOSO -Server SRV01234 -Protocol TCP`

Result:
```
Get-ADReplAccount : An item with the same key has already been added.
At line:1 char:1
+ Get-ADReplAccount -SamAccountName U123456 -Domain CONTOSO -Server SRV01234 -Prot ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADReplAccount], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,DSInternals.PowerShell.Commands.GetADReplAccountCommand
```

I tried many things to solve this:
- Changed the password
- Check the security on the object and removed and re enabled inheritance
- Move the account to a different OU
- Used on both domain controllers
- Used different admin account

No luck so far. Any tips ?

**Comment by MichaelGrafnetter** [comment]
Hi @CamFlyerCH , could you please send me the stack trace?

`$Error[0].Exception.StackTrace`

**Comment by CamFlyerCH** [comment]
Hi @MichaelGrafnetter 
Of corse, I forgot to get the full info. Here it is:

   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DSInternals.Replication.Model.ReplicaObject.LoadLinkedValues(ReplicatedLinkedValueCollection linkedValueCollection)
   at DSInternals.Replication.Interop.DrsConnection.ReadObjects(REPLENTINFLIST* objects, Int32 objectCount, __MIDL_drsuapi_0022* linkedValues, Int32 valueCount)
   at DSInternals.Replication.Interop.DrsConnection.ReplicateSingleObject(Guid objectGuid, UInt32[] partialAttributeSet)
   at DSInternals.Replication.DirectoryReplicationClient.GetAccount(Guid objectGuid)
   at DSInternals.PowerShell.Commands.GetADReplAccountCommand.ReturnSingleAccount()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

I hope that helps to find the problem.

**Comment by mattdreher** [comment]
I have a similar issue but I cannot pinpoint what account it is occurring on.  It happens when I use the -All syntax of Get-ADReplAccount

```
$arruserAndHashes = Get-ADReplAccount -All -NamingContext "DC=test,DC=test,DC=net" -Server DC01
Get-ADReplAccount : An item with the same key has already been added.
At line:1 char:21
+ ... AndHashes = Get-ADReplAccount -All -NamingContext "DC=test,DC=test ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADReplAccount], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,DSInternals.PowerShell.Commands.GetADReplAccountCommand
```

Here is my stack trace hoping it will help:
```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DSInternals.Replication.Model.ReplicaObject.LoadLinkedValues(ReplicatedLinkedValueCollection linkedValueCollection)
   at DSInternals.Replication.Interop.DrsConnection.ReadObjects(REPLENTINFLIST* objects, Int32 objectCount, __MIDL_drsuapi_0022* linkedValues, Int32 v
alueCount)
   at DSInternals.Replication.Interop.DrsConnection.ReplicateAllObjects(ReplicationCookie cookie, UInt32[] partialAttributeSet, UInt32 maxBytes, UInt3
2 maxObjects)
   at DSInternals.Replication.DirectoryReplicationClient.<GetAccounts>d__10.MoveNext()
   at DSInternals.PowerShell.Commands.GetADReplAccountCommand.ReturnAllAccounts()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by MichaelGrafnetter** [comment]
Thank you guys for thorough reports, I will look into it.

**Comment by MichaelGrafnetter** [comment]
@CamFlyerCH @mattdreher I have just released a new version of the module. Could you please test it? Thank you.

**Comment by CamFlyerCH** [comment]
Hello Michael
Work like a charm now !
Thanks !



Gruss
Jean-Marc

2017-04-14 19:56 GMT+02:00 Michael Grafnetter <notifications@github.com>:

**Comment by MichaelGrafnetter** [comment]
@CamFlyerCH Great, thanks for testing.

**Comment by mattdreher** [comment]
@MichaelGrafnetter , I have verified and it is working for me.  Thanks for the quick fix.

**Comment by MichaelGrafnetter** [comment]
Thank you, @mattdreher .
