### ISSUE TITLE
Test-PasswordQuality errors out with "Offset and length must refer to a position in the string"

### ISSUE THREAD

**Issue by lkarlslund** [MichaelGrafnetter/DSInternals#88]
Testing on a single account seems to work.

Testing on entire domain fails with this output:

```
PS C:\Users\MyUser> $accounts = Get-ADReplAccount -All -NamingContext 'DC=contoso,DC=com' -Server DC-01
PS C:\Users\MyUser> $accounts | Test-PasswordQuality -WeakPasswords 'weak','lame' -WeakPasswordHashesSortedFile 'c:\tools\pwned-passwords-ntlm-ordered-by-hash-v4.txt'
Test-PasswordQuality : Offset and length must refer to a position in the string.
Parameter name: string1
At line:1 char:13
+ $accounts | Test-PasswordQuality -WeakPasswords 'weak','lame'  -We ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Test-PasswordQuality], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,DSInternals.PowerShell.Commands.TestPasswordQualityCommand
```

**Comment by MichaelGrafnetter** [comment]
Thaks for reporting. I wonder if you could provide all info mentioned [here](https://github.com/MichaelGrafnetter/DSInternals/blob/master/.github/CONTRIBUTING.md#submitting-bug-reports), most importantly the exception stack trace.

**Comment by lkarlslund** [comment]
Sure! Here's the relevant data. It's not the AD controllers that are the problem, as the dump completes nicely.

```
PS C:\tools> # Error message
PS C:\tools> $Error[0].Exception.Message
Offset and length must refer to a position in the string.
Parameter name: string1
PS C:\tools>
PS C:\tools> # The entire exception stack trace
PS C:\tools> $Error[0].Exception.StackTrace
   at System.Globalization.CompareInfo.Compare(String string1, Int32 offset1, Int32 length1, String st
ring2, Int32 offset2, Int32 length2, CompareOptions options)
   at System.String.Compare(String strA, Int32 indexA, String strB, Int32 indexB, Int32 length, Boolea
n ignoreCase)
   at DSInternals.Common.Cryptography.SortedFileSearcher.FindString(String query)
   at DSInternals.PowerShell.Commands.TestPasswordQualityCommand.LookupAccountNTHashInSortedFile()
   at DSInternals.PowerShell.Commands.TestPasswordQualityCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PS C:\tools>
PS C:\tools> # Version of the DSInternals module
PS C:\tools> (Get-Module -Name DSInternals -ListAvailable).Version.ToString()
3.5
PS C:\tools>
PS C:\tools> # OS on which the command was running
PS C:\tools> (Get-WmiObject -Class Win32_OperatingSystem).Caption
Microsoft Windows Server 2019 Datacenter
```

**Comment by MichaelGrafnetter** [comment]
Hi @lkarlslund , could you please re-run the test with DSInternals 3.6 on the same input data? It should be working now.
