### ISSUE TITLE
Get-ADDBAccount : Could not decrypt or parse the PEK list.

### ISSUE THREAD

**Issue by Mescuphist** [MichaelGrafnetter/DSInternals#97]
Hello
Please help with at error
Get-ADDBAccount : Could not decrypt or parse the PEK list.

**Comment by MichaelGrafnetter** [comment]
Hi @Mescuphist , please send some more info, based on this [guide](https://github.com/MichaelGrafnetter/DSInternals/blob/master/.github/CONTRIBUTING.md#submitting-bug-reports).
Has this error occured in a test environment or in production?

**Comment by Mescuphist** [comment]
PS C:\WINDOWS\system32> $Error[0].Exception.Message
Could not decrypt or parse the PEK list.
PS C:\WINDOWS\system32> $Error[0].Exception.StackTrace
   at DSInternals.DataStore.DataStoreSecretDecryptor..ctor(Byte[] encryptedPEKListBlob, Byte[] bootKey) in d:\a\1\s\Src\DSInternals.DataStore\Cryptography\DataStoreSecretDecryptor.cs:line 87
   at DSInternals.DataStore.DirectoryAgent.GetSecretDecryptor(Byte[] bootKey) in d:\a\1\s\Src\DSInternals.DataStore\DirectoryAgent.PasswordManagement.cs:line 289
   at DSInternals.DataStore.DirectoryAgent.<GetAccounts>d__9.MoveNext() in d:\a\1\s\Src\DSInternals.DataStore\DirectoryAgent.cs:line 63
   at DSInternals.PowerShell.Commands.GetADDBAccountCommand.ReturnAllAccounts(Byte[] bootKey)
   at System.Management.Automation.CommandProcessor.ProcessRecord()

DSInternals_v3.6.1
$key = Get-BootKey -SystemHivePath 'SYSTEM'
$accounts = Get-ADDBAccount -All -DBPath 'Active Directory\ntds.dit' -BootKey $key

**Comment by MichaelGrafnetter** [comment]
Thx. What about the OS of the DC? WS 2016?
Also please provide the values from $Error[0].Exception.Data

**Comment by Mescuphist** [comment]
OS 2012R2 on DC
PS C:\WINDOWS\system32> $Error[0].Exception.Data

Name                           Value                                                                                                                                                                                                          
----                           -----                                                                                                                                                                                                          
encryptedPEKListBlob           0200000001000000f5b7027cd541bca0ace0742d3fc64ba7aafad3126d16df92f8a4e7d44bad028f140acdddd4f76d9d93e8eebfa7eabeab0c05fcd8c0267b3f009f9daaa60eccf0dd6285c3                                                       
bootKey                        b5a12df19bc5263699bf19d41b779526

**Comment by MichaelGrafnetter** [comment]
Thanks. I will analyze the data you sent, in order to figure out the root cause.

**Comment by Mescuphist** [comment]
Thank you

**Comment by MichaelGrafnetter** [comment]
This is really strange, as decryption of the binary data you sent works without any issues on my computer. Could you please also send the results of the following commands?

```powershell
$Error[0].Exception.InnerException.Message
$Error[0].Exception.InnerException.StackTrace
```

**Comment by Mescuphist** [comment]
PS C:\WINDOWS\system32> $Error[0].Exception.InnerException.Message
Exception has been thrown by the target of an invocation.

PS C:\WINDOWS\system32> $Error[0].Exception.InnerException.StackTrace
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at DSInternals.Common.Cryptography.DirectorySecretDecryptor.ComputeMD5(Byte[] key, Byte[] salt, Int32 saltHashRounds)
   at DSInternals.DataStore.DataStoreSecretDecryptor.DecryptPekList(Byte[] encryptedBlob, Byte[] bootKey) in d:\a\1\s\Src\DSInternals.DataStore\Cryptography\DataStoreSecretDecryptor.cs:line 332
   at DSInternals.DataStore.DataStoreSecretDecryptor..ctor(Byte[] encryptedPEKListBlob, Byte[] bootKey) in d:\a\1\s\Src\DSInternals.DataStore\Cryptography\DataStoreSecretDecryptor.cs:line 76

**Comment by MichaelGrafnetter** [comment]
OK, so it would seem that MD5 hash function is blocked on your system, as it is not FIPS compliant.
Could you please check the `FIPSAlgorithmPolicy` registry value under `HKLM\System\CurrentControlSet\Control\Lsa`?
Using the module on a different PC should resolve the issue. As an alternative, you could try merging this XML configuration into your `powershell.exe.config` or `powershell_ise.exe.config`:
```xml
<configuration>
  <runtime>
    <enforceFIPSPolicy enabled="false"/>
  </runtime>
</configuration>
```

**Comment by Mescuphist** [comment]
Thank you for help
problem resolved

**Comment by MichaelGrafnetter** [comment]
Great! So did you change the registry or XML? I have never actually tried it.

**Comment by Mescuphist** [comment]
Hello, im change the registry.
Quick question, can user passwords no longer be viewed in the report?
